source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!
inhibit_all_warnings!

use_frameworks!
inhibit_all_warnings!

def common_targets()
    # SWIFT LIB
pod 'SOAPEngine', '~> 1.31'
pod 'LLARingSpinnerView', '~> 0.1'
pod 'AFNetworking', '~> 2.6.3’

end

target 'gestaoSap' do
    common_targets
end

